In [1]:
# Imports 
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine

In [2]:
# get files to load

e_file = "resources/english.csv"
g_file = "resources/german.csv"
s_file = "resources/spanish.csv"

leagues_file = "resources/leagues.csv"

In [3]:
#load data into pandas dataframe

english = pd.read_csv(e_file)
german = pd.read_csv(g_file)
spanish = pd.read_csv(s_file)
leagues = pd.read_csv(leagues_file)

In [4]:
english.head()

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA,Matches
0,1,Patrick van Aanholt\Patrick-van-Aanholt,nl NED,DF,Crystal Palace,27,1990,36,36,3195,...,0.14,2.7,2.7,3.9,0.08,0.11,0.19,0.08,0.19,Matches
1,2,Sergio Agüero\Sergio-Aguero,ar ARG,FW,Manchester City,30,1988,33,31,2459,...,0.99,20.7,19.2,5.5,0.76,0.20,0.96,0.70,0.91,Matches
2,3,Nathan Aké\Nathan-Ake,nl NED,DF,Bournemouth,23,1995,38,38,3411,...,0.11,3.4,3.4,0.8,0.09,0.02,0.11,0.09,0.11,Matches
3,4,Marc Albrighton\Marc-Albrighton,eng ENG,FWMF,Leicester City,28,1989,27,18,1625,...,0.22,1.1,1.1,3.1,0.06,0.17,0.23,0.06,0.23,Matches
4,5,Toby Alderweireld\Toby-Alderweireld,be BEL,DF,Tottenham,29,1989,34,33,2922,...,0.00,1.1,1.1,0.6,0.03,0.02,0.05,0.03,0.05,Matches

In [5]:
german.head()

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA,Matches
0,1,Issah Abbas\Issah-Abbas,gh GHA,FW,Mainz 05,19,1998,1,0,9,...,0.00,0.0,0.0,0.0,0.17,0.00,0.17,0.17,0.17,Matches
1,2,David Abraham\David-Abraham,ar ARG,DF,Eint Frankfurt,32,1986,17,17,1420,...,0.00,0.4,0.4,0.1,0.03,0.01,0.03,0.03,0.03,Matches
2,3,Amir Abrashi\Amir-Abrashi,al ALB,MF,Freiburg,28,1990,10,9,790,...,0.00,0.2,0.2,0.1,0.02,0.01,0.02,0.02,0.02,Matches
3,4,Tyler Adams\Tyler-Adams,us USA,MF,RB Leipzig,19,1999,10,8,721,...,0.25,0.2,0.2,0.7,0.03,0.09,0.12,0.03,0.12,Matches
4,5,Antonis Aidonis\Antonis-Aidonis,de GER,DF,Stuttgart,17,2001,2,1,80,...,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,Matches

In [6]:
spanish.head()

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA,Matches
0,1,Antonio Adán\Antonio-Adan,es ESP,GK,Atlético Madrid,31.0,1987.0,1,1,90,...,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,Matches
1,2,Aday\Aday,es ESP,DFMF,Girona,30.0,1987.0,10,8,645,...,0.28,0.2,0.2,0.8,0.03,0.11,0.14,0.03,0.14,Matches
2,3,Aritz Aduriz\Aritz-Aduriz,es ESP,FW,Athletic Club,37.0,1981.0,20,10,943,...,0.00,3.3,1.8,0.4,0.32,0.04,0.36,0.17,0.21,Matches
3,4,Luis Advíncula\Luis-Advincula,pe PER,DF,Rayo Vallecano,28.0,1990.0,28,27,2389,...,0.15,0.9,0.9,1.9,0.03,0.07,0.10,0.03,0.10,Matches
4,5,Martin Agirregabiria\Martin-Agirregabiria,es ESP,DF,Alavés,22.0,1996.0,27,23,2032,...,0.00,0.1,0.1,0.4,0.01,0.02,0.02,0.01,0.02,Matches

In [7]:
leagues.head()

            League Confederation  Country  No_Teams
0  Premiere League          UEFA  England        20
1       Bundesliga          UEFA  Germany        18
2          La Liga          UEFA    Spain        20

In [8]:
# displays all the column names in the spanish, german, and english dataframes

for col in spanish.columns:
    print(col)

Rk
Player
Nation
Pos
Squad
Age
Born
MP
Starts
Min
Gls
Ast
PK
PKatt
CrdY
CrdR
Gls.1
Ast.1
G+A
G-PK
G+A-PK
xG
npxG
xA
xG.1
xA.1
xG+xA
npxG.1
npxG+xA
Matches

In [9]:
def df_cleanup(country):
    new = country["Player"].str.split('\\', n = 1, expand = True)
    country["Player_Name"]= new[0]
    country['Nation'] = country['Nation'].str[3:]
    country['Pos'] = country['Pos'].str[:2]

In [10]:
df_cleanup(spanish)

In [11]:
spanish.head()

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA,Matches,Player_Name
0,1,Antonio Adán\Antonio-Adan,ESP,GK,Atlético Madrid,31.0,1987.0,1,1,90,...,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,Matches,Antonio Adán
1,2,Aday\Aday,ESP,DF,Girona,30.0,1987.0,10,8,645,...,0.2,0.2,0.8,0.03,0.11,0.14,0.03,0.14,Matches,Aday
2,3,Aritz Aduriz\Aritz-Aduriz,ESP,FW,Athletic Club,37.0,1981.0,20,10,943,...,3.3,1.8,0.4,0.32,0.04,0.36,0.17,0.21,Matches,Aritz Aduriz
3,4,Luis Advíncula\Luis-Advincula,PER,DF,Rayo Vallecano,28.0,1990.0,28,27,2389,...,0.9,0.9,1.9,0.03,0.07,0.10,0.03,0.10,Matches,Luis Advíncula
4,5,Martin Agirregabiria\Martin-Agirregabiria,ESP,DF,Alavés,22.0,1996.0,27,23,2032,...,0.1,0.1,0.4,0.01,0.02,0.02,0.01,0.02,Matches,Martin Agirregabiria

In [12]:
cols = list(spanish.columns.values)
cols

['Rk',
 'Player',
 'Nation',
 'Pos',
 'Squad',
 'Age',
 'Born',
 'MP',
 'Starts',
 'Min',
 'Gls',
 'Ast',
 'PK',
 'PKatt',
 'CrdY',
 'CrdR',
 'Gls.1',
 'Ast.1',
 'G+A',
 'G-PK',
 'G+A-PK',
 'xG',
 'npxG',
 'xA',
 'xG.1',
 'xA.1',
 'xG+xA',
 'npxG.1',
 'npxG+xA',
 'Matches',
 'Player_Name']

In [13]:
spanish["League"]= "La Liga"

In [14]:
# rearrange the columns and drop duplicate name columns
spanish = spanish[['Player_Name','Nation', 'League',
 'Pos',
 'Squad',
 'Age',
 'Born',
 'MP',
 'Starts',
 'Min',
 'Gls',
 'Ast',
 'PK',
 'PKatt',
 'CrdY',
 'CrdR',
 'Gls.1',
 'Ast.1',
 'G+A',
 'G-PK',
 'G+A-PK',
 'xG',
 'npxG',
 'xA',
 'xG.1',
 'xA.1',
 'xG+xA',
 'npxG.1',
 'npxG+xA']]

In [15]:
spanish.head()

,Player_Name,Nation,League,Pos,Squad,Age,Born,MP,Starts,Min,...,G-PK,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA
0,Antonio Adán,ESP,La Liga,GK,Atlético Madrid,31.0,1987.0,1,1,90,...,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
1,Aday,ESP,La Liga,DF,Girona,30.0,1987.0,10,8,645,...,0.00,0.28,0.2,0.2,0.8,0.03,0.11,0.14,0.03,0.14
2,Aritz Aduriz,ESP,La Liga,FW,Athletic Club,37.0,1981.0,20,10,943,...,0.00,0.00,3.3,1.8,0.4,0.32,0.04,0.36,0.17,0.21
3,Luis Advíncula,PER,La Liga,DF,Rayo Vallecano,28.0,1990.0,28,27,2389,...,0.04,0.15,0.9,0.9,1.9,0.03,0.07,0.10,0.03,0.10
4,Martin Agirregabiria,ESP,La Liga,DF,Alavés,22.0,1996.0,27,23,2032,...,0.00,0.00,0.1,0.1,0.4,0.01,0.02,0.02,0.01,0.02

In [16]:
df_cleanup(english)

In [17]:
english["League"]= "Premiere League"

In [18]:
# rearrange the columns and drop duplicate name columns
english = english[['Player_Name','Nation', 'League',
 'Pos',
 'Squad',
 'Age',
 'Born',
 'MP',
 'Starts',
 'Min',
 'Gls',
 'Ast',
 'PK',
 'PKatt',
 'CrdY',
 'CrdR',
 'Gls.1',
 'Ast.1',
 'G+A',
 'G-PK',
 'G+A-PK',
 'xG',
 'npxG',
 'xA',
 'xG.1',
 'xA.1',
 'xG+xA',
 'npxG.1',
 'npxG+xA']]

In [19]:
english.head()

,Player_Name,Nation,League,Pos,Squad,Age,Born,MP,Starts,Min,...,G-PK,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA
0,Patrick van Aanholt,NED,Premiere League,DF,Crystal Palace,27,1990,36,36,3195,...,0.08,0.14,2.7,2.7,3.9,0.08,0.11,0.19,0.08,0.19
1,Sergio Agüero,ARG,Premiere League,FW,Manchester City,30,1988,33,31,2459,...,0.70,0.99,20.7,19.2,5.5,0.76,0.20,0.96,0.70,0.91
2,Nathan Aké,NED,Premiere League,DF,Bournemouth,23,1995,38,38,3411,...,0.11,0.11,3.4,3.4,0.8,0.09,0.02,0.11,0.09,0.11
3,Marc Albrighton,ENG,Premiere League,FW,Leicester City,28,1989,27,18,1625,...,0.11,0.22,1.1,1.1,3.1,0.06,0.17,0.23,0.06,0.23
4,Toby Alderweireld,BEL,Premiere League,DF,Tottenham,29,1989,34,33,2922,...,0.00,0.00,1.1,1.1,0.6,0.03,0.02,0.05,0.03,0.05

In [20]:
df_cleanup(german)

In [21]:
german["League"]= "Bundesliga"

In [22]:
# rearrange the columns and drop duplicate name columns
german = german[['Player_Name','Nation', "League",
 'Pos',
 'Squad',
 'Age',
 'Born',
 'MP',
 'Starts',
 'Min',
 'Gls',
 'Ast',
 'PK',
 'PKatt',
 'CrdY',
 'CrdR',
 'Gls.1',
 'Ast.1',
 'G+A',
 'G-PK',
 'G+A-PK',
 'xG',
 'npxG',
 'xA',
 'xG.1',
 'xA.1',
 'xG+xA',
 'npxG.1',
 'npxG+xA']]

In [23]:
german.head()

,Player_Name,Nation,League,Pos,Squad,Age,Born,MP,Starts,Min,...,G-PK,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA
0,Issah Abbas,GHA,Bundesliga,FW,Mainz 05,19,1998,1,0,9,...,0.0,0.00,0.0,0.0,0.0,0.17,0.00,0.17,0.17,0.17
1,David Abraham,ARG,Bundesliga,DF,Eint Frankfurt,32,1986,17,17,1420,...,0.0,0.00,0.4,0.4,0.1,0.03,0.01,0.03,0.03,0.03
2,Amir Abrashi,ALB,Bundesliga,MF,Freiburg,28,1990,10,9,790,...,0.0,0.00,0.2,0.2,0.1,0.02,0.01,0.02,0.02,0.02
3,Tyler Adams,USA,Bundesliga,MF,RB Leipzig,19,1999,10,8,721,...,0.0,0.25,0.2,0.2,0.7,0.03,0.09,0.12,0.03,0.12
4,Antonis Aidonis,GER,Bundesliga,DF,Stuttgart,17,2001,2,1,80,...,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00

In [24]:
all_players = pd.concat([spanish, german, english])

In [25]:
all_players

,Player_Name,Nation,League,Pos,Squad,Age,Born,MP,Starts,Min,...,G-PK,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA
0,Antonio Adán,ESP,La Liga,GK,Atlético Madrid,31.0,1987.0,1,1,90,...,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
1,Aday,ESP,La Liga,DF,Girona,30.0,1987.0,10,8,645,...,0.00,0.28,0.2,0.2,0.8,0.03,0.11,0.14,0.03,0.14
2,Aritz Aduriz,ESP,La Liga,FW,Athletic Club,37.0,1981.0,20,10,943,...,0.00,0.00,3.3,1.8,0.4,0.32,0.04,0.36,0.17,0.21
3,Luis Advíncula,PER,La Liga,DF,Rayo Vallecano,28.0,1990.0,28,27,2389,...,0.04,0.15,0.9,0.9,1.9,0.03,0.07,0.10,0.03,0.10
4,Martin Agirregabiria,ESP,La Liga,DF,Alavés,22.0,1996.0,27,23,2032,...,0.00,0.00,0.1,0.1,0.4,0.01,0.02,0.02,0.01,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,Andre-Frank Zambo Anguissa,CMR,Premiere League,MF,Fulham,22.0,1995.0,22,16,1517,...,0.00,0.00,0.8,0.8,0.4,0.05,0.02,0.07,0.05,0.07
504,Davide Zappacosta,ITA,Premiere League,DF,Chelsea,26.0,1992.0,4,1,128,...,0.00,0.00,0.1,0.1,0.1,0.04,0.10,0.14,0.04,0.14
505,Oleksandr Zinchenko,UKR,Premiere League,DF,Manchester City,21.0,1996.0,14,14,1151,...,0.00,0.23,0.1,0.1,1.3,0.01,0.10,0.11,0.01,0.11
506,Kenneth Zohore,DEN,Premiere League,FW,Cardiff City,24.0,1994.0,19,7,753,...,0.12,0.24,1.9,1.9,1.1,0.22,0.13,0.35,0.22,0.35
507,Kurt Zouma,FRA,Premiere League,DF,Everton,23.0,1994.0,32,29,2612,...,0.07,0.14,1.3,1.3,0.3,0.04,0.01,0.06,0.04,0.06

In [26]:
all_players = all_players[['Player_Name','Nation', 'League','Squad','Pos','Age','Born']]

In [27]:
all_players

,Player_Name,Nation,League,Squad,Pos,Age,Born
0,Antonio Adán,ESP,La Liga,Atlético Madrid,GK,31.0,1987.0
1,Aday,ESP,La Liga,Girona,DF,30.0,1987.0
2,Aritz Aduriz,ESP,La Liga,Athletic Club,FW,37.0,1981.0
3,Luis Advíncula,PER,La Liga,Rayo Vallecano,DF,28.0,1990.0
4,Martin Agirregabiria,ESP,La Liga,Alavés,DF,22.0,1996.0
...,...,...,...,...,...,...,...
503,Andre-Frank Zambo Anguissa,CMR,Premiere League,Fulham,MF,22.0,1995.0
504,Davide Zappacosta,ITA,Premiere League,Chelsea,DF,26.0,1992.0
505,Oleksandr Zinchenko,UKR,Premiere League,Manchester City,DF,21.0,1996.0
506,Kenneth Zohore,DEN,Premiere League,Cardiff City,FW,24.0,1994.0
507,Kurt Zouma,FRA,Premiere League,Everton,DF,23.0,1994.0

In [28]:
bundesliga_stats = german[['Player_Name',
 'MP',
 'Starts',
 'Min',
 'Gls',
 'Ast',
 'PK',
 'PKatt',
 'CrdY',
 'CrdR',
 'Gls.1',
 'Ast.1',
 'G+A',
 'G-PK',
 'G+A-PK',
 'xG',
 'npxG',
 'xA',
 'xG.1',
 'xA.1',
 'xG+xA',
 'npxG.1',
 'npxG+xA']]

In [29]:
bundesliga_stats.head()

,Player_Name,MP,Starts,Min,Gls,Ast,PK,PKatt,CrdY,CrdR,...,G-PK,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA
0,Issah Abbas,1,0,9,0,0,0,0,0,0,...,0.0,0.00,0.0,0.0,0.0,0.17,0.00,0.17,0.17,0.17
1,David Abraham,17,17,1420,0,0,0,0,2,0,...,0.0,0.00,0.4,0.4,0.1,0.03,0.01,0.03,0.03,0.03
2,Amir Abrashi,10,9,790,0,0,0,0,5,0,...,0.0,0.00,0.2,0.2,0.1,0.02,0.01,0.02,0.02,0.02
3,Tyler Adams,10,8,721,0,2,0,0,0,0,...,0.0,0.25,0.2,0.2,0.7,0.03,0.09,0.12,0.03,0.12
4,Antonis Aidonis,2,1,80,0,0,0,0,1,0,...,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00

In [30]:
laliga_stats = spanish[['Player_Name',
 'MP',
 'Starts',
 'Min',
 'Gls',
 'Ast',
 'PK',
 'PKatt',
 'CrdY',
 'CrdR',
 'Gls.1',
 'Ast.1',
 'G+A',
 'G-PK',
 'G+A-PK',
 'xG',
 'npxG',
 'xA',
 'xG.1',
 'xA.1',
 'xG+xA',
 'npxG.1',
 'npxG+xA']]

In [31]:
laliga_stats.head()

,Player_Name,MP,Starts,Min,Gls,Ast,PK,PKatt,CrdY,CrdR,...,G-PK,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA
0,Antonio Adán,1,1,90,0,0,0,0,1,0,...,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
1,Aday,10,8,645,0,2,0,0,2,0,...,0.00,0.28,0.2,0.2,0.8,0.03,0.11,0.14,0.03,0.14
2,Aritz Aduriz,20,10,943,2,0,2,2,5,0,...,0.00,0.00,3.3,1.8,0.4,0.32,0.04,0.36,0.17,0.21
3,Luis Advíncula,28,27,2389,1,3,0,0,6,2,...,0.04,0.15,0.9,0.9,1.9,0.03,0.07,0.10,0.03,0.10
4,Martin Agirregabiria,27,23,2032,0,0,0,0,4,0,...,0.00,0.00,0.1,0.1,0.4,0.01,0.02,0.02,0.01,0.02

In [32]:
premiere_stats = english[['Player_Name',
 'MP',
 'Starts',
 'Min',
 'Gls',
 'Ast',
 'PK',
 'PKatt',
 'CrdY',
 'CrdR',
 'Gls.1',
 'Ast.1',
 'G+A',
 'G-PK',
 'G+A-PK',
 'xG',
 'npxG',
 'xA',
 'xG.1',
 'xA.1',
 'xG+xA',
 'npxG.1',
 'npxG+xA']]

In [33]:
premiere_stats.head()

,Player_Name,MP,Starts,Min,Gls,Ast,PK,PKatt,CrdY,CrdR,...,G-PK,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA
0,Patrick van Aanholt,36,36,3195,3,2,0,0,3,0,...,0.08,0.14,2.7,2.7,3.9,0.08,0.11,0.19,0.08,0.19
1,Sergio Agüero,33,31,2459,21,8,2,2,4,0,...,0.70,0.99,20.7,19.2,5.5,0.76,0.20,0.96,0.70,0.91
2,Nathan Aké,38,38,3411,4,0,0,0,3,0,...,0.11,0.11,3.4,3.4,0.8,0.09,0.02,0.11,0.09,0.11
3,Marc Albrighton,27,18,1625,2,2,0,0,3,0,...,0.11,0.22,1.1,1.1,3.1,0.06,0.17,0.23,0.06,0.23
4,Toby Alderweireld,34,33,2922,0,0,0,0,3,0,...,0.00,0.00,1.1,1.1,0.6,0.03,0.02,0.05,0.03,0.05

In [34]:
leagues.set_index("League", inplace=True)

In [35]:
leagues.head()

                Confederation  Country  No_Teams
League
Premiere League          UEFA  England        20
Bundesliga               UEFA  Germany        18
La Liga                  UEFA    Spain        20

In [36]:
bundesliga_stats.set_index("Player_Name", inplace=True)
laliga_stats.set_index("Player_Name", inplace=True)
premiere_stats.set_index("Player_Name", inplace=True)

In [37]:
bundesliga_stats.head()

,MP,Starts,Min,Gls,Ast,PK,PKatt,CrdY,CrdR,Gls.1,...,G-PK,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA
Player_Name,,,,,,,,,,,,,,,,,,,,,
Issah Abbas,1,0,9,0,0,0,0,0,0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.17,0.00,0.17,0.17,0.17
David Abraham,17,17,1420,0,0,0,0,2,0,0.0,...,0.0,0.00,0.4,0.4,0.1,0.03,0.01,0.03,0.03,0.03
Amir Abrashi,10,9,790,0,0,0,0,5,0,0.0,...,0.0,0.00,0.2,0.2,0.1,0.02,0.01,0.02,0.02,0.02
Tyler Adams,10,8,721,0,2,0,0,0,0,0.0,...,0.0,0.25,0.2,0.2,0.7,0.03,0.09,0.12,0.03,0.12
Antonis Aidonis,2,1,80,0,0,0,0,1,0,0.0,...,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00

In [38]:
laliga_stats.head()

,MP,Starts,Min,Gls,Ast,PK,PKatt,CrdY,CrdR,Gls.1,...,G-PK,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA
Player_Name,,,,,,,,,,,,,,,,,,,,,
Antonio Adán,1,1,90,0,0,0,0,1,0,0.00,...,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
Aday,10,8,645,0,2,0,0,2,0,0.00,...,0.00,0.28,0.2,0.2,0.8,0.03,0.11,0.14,0.03,0.14
Aritz Aduriz,20,10,943,2,0,2,2,5,0,0.19,...,0.00,0.00,3.3,1.8,0.4,0.32,0.04,0.36,0.17,0.21
Luis Advíncula,28,27,2389,1,3,0,0,6,2,0.04,...,0.04,0.15,0.9,0.9,1.9,0.03,0.07,0.10,0.03,0.10
Martin Agirregabiria,27,23,2032,0,0,0,0,4,0,0.00,...,0.00,0.00,0.1,0.1,0.4,0.01,0.02,0.02,0.01,0.02

In [39]:
premiere_stats.head()

,MP,Starts,Min,Gls,Ast,PK,PKatt,CrdY,CrdR,Gls.1,...,G-PK,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA
Player_Name,,,,,,,,,,,,,,,,,,,,,
Patrick van Aanholt,36,36,3195,3,2,0,0,3,0,0.08,...,0.08,0.14,2.7,2.7,3.9,0.08,0.11,0.19,0.08,0.19
Sergio Agüero,33,31,2459,21,8,2,2,4,0,0.77,...,0.70,0.99,20.7,19.2,5.5,0.76,0.20,0.96,0.70,0.91
Nathan Aké,38,38,3411,4,0,0,0,3,0,0.11,...,0.11,0.11,3.4,3.4,0.8,0.09,0.02,0.11,0.09,0.11
Marc Albrighton,27,18,1625,2,2,0,0,3,0,0.11,...,0.11,0.22,1.1,1.1,3.1,0.06,0.17,0.23,0.06,0.23
Toby Alderweireld,34,33,2922,0,0,0,0,3,0,0.00,...,0.00,0.00,1.1,1.1,0.6,0.03,0.02,0.05,0.03,0.05

In [40]:
all_players.set_index("Player_Name", inplace=True)

In [41]:
all_players.head()

                     Nation   League            Squad Pos   Age    Born
Player_Name
Antonio Adán            ESP  La Liga  Atlético Madrid  GK  31.0  1987.0
Aday                    ESP  La Liga           Girona  DF  30.0  1987.0
Aritz Aduriz            ESP  La Liga    Athletic Club  FW  37.0  1981.0
Luis Advíncula          PER  La Liga   Rayo Vallecano  DF  28.0  1990.0
Martin Agirregabiria    ESP  La Liga           Alavés  DF  22.0  1996.0

In [42]:
#Load

In [43]:
engine = create_engine('sqlite:///leagues.db', echo=True)
sqlite_connection = engine.connect()

2020-09-02 18:58:13,375 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2020-09-02 18:58:13,376 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:13,377 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2020-09-02 18:58:13,378 INFO sqlalchemy.engine.base.Engine ()

In [44]:
table = "SoccerLeagues"
leagues.to_sql(table, sqlite_connection, if_exists="replace")
english.to_sql(table, sqlite_connection, if_exists="replace")
german.to_sql(table, sqlite_connection, if_exists="replace")
spanish.to_sql(table, sqlite_connection, if_exists="replace")

2020-09-02 18:58:14,047 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("SoccerLeagues")
2020-09-02 18:58:14,048 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,049 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("SoccerLeagues")
2020-09-02 18:58:14,049 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,051 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "SoccerLeagues" (
	"League" TEXT,
	"Confederation" TEXT,
	"Country" TEXT,
	"No_Teams" BIGINT
)


2020-09-02 18:58:14,051 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,053 INFO sqlalchemy.engine.base.Engine COMMIT
2020-09-02 18:58:14,053 INFO sqlalchemy.engine.base.Engine CREATE INDEX "ix_SoccerLeagues_League" ON "SoccerLeagues" ("League")
2020-09-02 18:58:14,054 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,056 INFO sqlalchemy.engine.base.Engine COMMIT
2020-09-02 18:58:14,058 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-09-02 18:58:14,060 INFO sqlalchemy.engine.base.Engine INSERT INTO "SoccerLeagues" ("League", "Confederation", "Country", "No_Teams") VALUES (?, ?, ?, ?)
2020-09-02 18:58:14,060 INFO sqlalchemy.engine.base.Engine (('Premiere League', 'UEFA', 'England', 20), ('Bundesliga', 'UEFA', 'Germany', 18), ('La Liga', 'UEFA', 'Spain', 20))
2020-09-02 18:58:14,061 INFO sqlalchemy.engine.base.Engine COMMIT
2020-09-02 18:58:14,063 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2020-09-02 18:58:14,063 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,069 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("SoccerLeagues")
2020-09-02 18:58:14,070 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,071 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("SoccerLeagues")
2020-09-02 18:58:14,071 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,072 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2020-09-02 18:58:14,073 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,075 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_xinfo("SoccerLeagues")
2020-09-02 18:58:14,076 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,078 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'SoccerLeagues' AND type = 'table'
2020-09-02 18:58:14,079 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,081 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("SoccerLeagues")
2020-09-02 18:58:14,081 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,082 INFO sqlalchemy.engine.base.Engine PRAGMA temp.foreign_key_list("SoccerLeagues")
2020-09-02 18:58:14,083 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,083 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'SoccerLeagues' AND type = 'table'
2020-09-02 18:58:14,084 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,086 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("SoccerLeagues")
2020-09-02 18:58:14,086 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,087 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_SoccerLeagues_League")
2020-09-02 18:58:14,087 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,088 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("SoccerLeagues")
2020-09-02 18:58:14,089 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,090 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_SoccerLeagues_League")
2020-09-02 18:58:14,090 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,091 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'SoccerLeagues' AND type = 'table'
2020-09-02 18:58:14,092 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,094 INFO sqlalchemy.engine.base.Engine
DROP TABLE "SoccerLeagues"
2020-09-02 18:58:14,094 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,096 INFO sqlalchemy.engine.base.Engine COMMIT
2020-09-02 18:58:14,100 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "SoccerLeagues" (
	"index" BIGINT,
	"Player_Name" TEXT,
	"Nation" TEXT,
	"League" TEXT,
	"Pos" TEXT,
	"Squad" TEXT,
	"Age" BIGINT,
	"Born" BIGINT,
	"MP" BIGINT,
	"Starts" BIGINT,
	"Min" BIGINT,
	"Gls" BIGINT,
	"Ast" BIGINT,
	"PK" BIGINT,
	"PKatt" BIGINT,
	"CrdY" BIGINT,
	"CrdR" BIGINT,
	"Gls.1" FLOAT,
	"Ast.1" FLOAT,
	"G+A" FLOAT,
	"G-PK" FLOAT,
	"G+A-PK" FLOAT,
	"xG" FLOAT,
	"npxG" FLOAT,
	"xA" FLOAT,
	"xG.1" FLOAT,
	"xA.1" FLOAT,
	"xG+xA" FLOAT,
	"npxG.1" FLOAT,
	"npxG+xA" FLOAT
)


2020-09-02 18:58:14,101 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,103 INFO sqlalchemy.engine.base.Engine COMMIT
2020-09-02 18:58:14,104 INFO sqlalchemy.engine.base.Engine CREATE INDEX "ix_SoccerLeagues_index" ON "SoccerLeagues" ("index")
2020-09-02 18:58:14,105 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,107 INFO sqlalchemy.engine.base.Engine COMMIT
2020-09-02 18:58:14,111 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-09-02 18:58:14,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "SoccerLeagues" ("index", "Player_Name", "Nation", "League", "Pos", "Squad", "Age", "Born", "MP", "Starts", "Min", "Gls", "Ast", "PK", "PKatt", "CrdY", "CrdR", "Gls.1", "Ast.1", "G+A", "G-PK", "G+A-PK", "xG", "npxG", "xA", "xG.1", "xA.1", "xG+xA", "npxG.1", "npxG+xA") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2020-09-02 18:58:14,129 INFO sqlalchemy.engine.base.Engine ((0, 'Patrick van Aanholt', 'NED', 'Premiere League', 'DF', 'Crystal Palace', 27, 1990, 36, 36, 3195, 3, 2, 0, 0, 3, 0, 0.08, 0.06, 0.14, 0.08, 0.14, 2.7, 2.7, 3.9, 0.08, 0.11, 0.19, 0.08, 0.19), (1, 'Sergio Agüero', 'ARG', 'Premiere League', 'FW', 'Manchester City', 30, 1988, 33, 31, 2459, 21, 8, 2, 2, 4, 0, 0.77, 0.29, 1.06, 0.7, 0.99, 20.7, 19.2, 5.5, 0.76, 0.2, 0.96, 0.7, 0.91), (2, 'Nathan Aké', 'NED', 'Premiere League', 'DF', 'Bournemouth', 23, 1995, 38, 38, 3411, 4, 0, 0, 0, 3, 0, 0.11, 0.0, 0.11, 0.11, 0.11, 3.4, 3.4, 0.8, 0.09, 0.02, 0.11, 0.09, 0.11), (3, 'Marc Albrighton', ' ENG', 'Premiere League', 'FW', 'Leicester City', 28, 1989, 27, 18, 1625, 2, 2, 0, 0, 3, 0, 0.11, 0.11, 0.22, 0.11, 0.22, 1.1, 1.1, 3.1, 0.06, 0.17, 0.23, 0.06, 0.23), (4, 'Toby Alderweireld', 'BEL', 'Premiere League', 'DF', 'Tottenham', 29, 1989, 34, 33, 2922, 0, 0, 0, 0, 3, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.1, 1.1, 0.6, 0.03, 0.02, 0.05, 0.03, 0.05), (5, 'Trent Alexander-Arnold', ' ENG', 'Premiere League', 'DF', 'Liverpool', 19, 1998, 29, 27, 2462, 1, 12, 0, 0, 3, 0, 0.04, 0.44, 0.48, 0.04, 0.48, 1.5, 1.5, 6.1, 0.05, 0.22, 0.28, 0.05, 0.28), (6, 'Alisson', 'BRA', 'Premiere League', 'GK', 'Liverpool', 25, 1992, 38, 38, 3420, 0, 0, 0, 0, 1, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0), (7, 'Dele Alli', ' ENG', 'Premiere League', 'MF', 'Tottenham', 22, 1996, 25, 22, 1825, 5, 3, 0, 0, 4, 0, 0.25, 0.15, 0.39, 0.25, 0.39, 5.3, 5.3, 2.4, 0.26, 0.12, 0.38, 0.26, 0.38)  ... displaying 10 of 508 total bound parameter sets ...  (506, 'Kenneth Zohore', 'DEN', 'Premiere League', 'FW', 'Cardiff City', 24, 1994, 19, 7, 753, 1, 1, 0, 0, 1, 0, 0.12, 0.12, 0.24, 0.12, 0.24, 1.9, 1.9, 1.1, 0.22, 0.13, 0.35, 0.22, 0.35), (507, 'Kurt Zouma', 'FRA', 'Premiere League', 'DF', 'Everton', 23, 1994, 32, 29, 2612, 2, 2, 0, 0, 4, 1, 0.07, 0.07, 0.14, 0.07, 0.14, 1.3, 1.3, 0.3, 0.04, 0.01, 0.06, 0.04, 0.06))
2020-09-02 18:58:14,146 INFO sqlalchemy.engine.base.Engine COMMIT
2020-09-02 18:58:14,148 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2020-09-02 18:58:14,148 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,153 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("SoccerLeagues")
2020-09-02 18:58:14,154 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,155 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("SoccerLeagues")
2020-09-02 18:58:14,155 INFO sqlalchemy.engine.base.Engine ()

2020-09-02 18:58:14,157 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2020-09-02 18:58:14,158 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,159 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_xinfo("SoccerLeagues")
2020-09-02 18:58:14,159 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,164 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'SoccerLeagues' AND type = 'table'
2020-09-02 18:58:14,165 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,166 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("SoccerLeagues")
2020-09-02 18:58:14,166 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,167 INFO sqlalchemy.engine.base.Engine PRAGMA temp.foreign_key_list("SoccerLeagues")
2020-09-02 18:58:14,168 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,168 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'SoccerLeagues' AND type = 'table'
2020-09-02 18:58:14,169 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,170 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("SoccerLeagues")
2020-09-02 18:58:14,170 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,171 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_SoccerLeagues_index")
2020-09-02 18:58:14,171 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,172 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("SoccerLeagues")
2020-09-02 18:58:14,173 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,173 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_SoccerLeagues_index")
2020-09-02 18:58:14,174 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,174 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'SoccerLeagues' AND type = 'table'
2020-09-02 18:58:14,175 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,177 INFO sqlalchemy.engine.base.Engine
DROP TABLE "SoccerLeagues"
2020-09-02 18:58:14,178 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,181 INFO sqlalchemy.engine.base.Engine COMMIT
2020-09-02 18:58:14,185 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "SoccerLeagues" (
	"index" BIGINT,
	"Player_Name" TEXT,
	"Nation" TEXT,
	"League" TEXT,
	"Pos" TEXT,
	"Squad" TEXT,
	"Age" BIGINT,
	"Born" BIGINT,
	"MP" BIGINT,
	"Starts" BIGINT,
	"Min" BIGINT,
	"Gls" BIGINT,
	"Ast" BIGINT,
	"PK" BIGINT,
	"PKatt" BIGINT,
	"CrdY" BIGINT,
	"CrdR" BIGINT,
	"Gls.1" FLOAT,
	"Ast.1" FLOAT,
	"G+A" FLOAT,
	"G-PK" FLOAT,
	"G+A-PK" FLOAT,
	"xG" FLOAT,
	"npxG" FLOAT,
	"xA" FLOAT,
	"xG.1" FLOAT,
	"xA.1" FLOAT,
	"xG+xA" FLOAT,
	"npxG.1" FLOAT,
	"npxG+xA" FLOAT
)


2020-09-02 18:58:14,186 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,187 INFO sqlalchemy.engine.base.Engine COMMIT
2020-09-02 18:58:14,188 INFO sqlalchemy.engine.base.Engine CREATE INDEX "ix_SoccerLeagues_index" ON "SoccerLeagues" ("index")
2020-09-02 18:58:14,189 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,190 INFO sqlalchemy.engine.base.Engine COMMIT
2020-09-02 18:58:14,193 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-09-02 18:58:14,209 INFO sqlalchemy.engine.base.Engine INSERT INTO "SoccerLeagues" ("index", "Player_Name", "Nation", "League", "Pos", "Squad", "Age", "Born", "MP", "Starts", "Min", "Gls", "Ast", "PK", "PKatt", "CrdY", "CrdR", "Gls.1", "Ast.1", "G+A", "G-PK", "G+A-PK", "xG", "npxG", "xA", "xG.1", "xA.1", "xG+xA", "npxG.1", "npxG+xA") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2020-09-02 18:58:14,210 INFO sqlalchemy.engine.base.Engine ((0, 'Issah Abbas', 'GHA', 'Bundesliga', 'FW', 'Mainz 05', 19, 1998, 1, 0, 9, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.17, 0.0, 0.17, 0.17, 0.17), (1, 'David Abraham', 'ARG', 'Bundesliga', 'DF', 'Eint Frankfurt', 32, 1986, 17, 17, 1420, 0, 0, 0, 0, 2, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 0.4, 0.1, 0.03, 0.01, 0.03, 0.03, 0.03), (2, 'Amir Abrashi', 'ALB', 'Bundesliga', 'MF', 'Freiburg', 28, 1990, 10, 9, 790, 0, 0, 0, 0, 5, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, 0.1, 0.02, 0.01, 0.02, 0.02, 0.02), (3, 'Tyler Adams', 'USA', 'Bundesliga', 'MF', 'RB Leipzig', 19, 1999, 10, 8, 721, 0, 2, 0, 0, 0, 0, 0.0, 0.25, 0.25, 0.0, 0.25, 0.2, 0.2, 0.7, 0.03, 0.09, 0.12, 0.03, 0.12), (4, 'Antonis Aidonis', 'GER', 'Bundesliga', 'DF', 'Stuttgart', 17, 2001, 2, 1, 80, 0, 0, 0, 0, 1, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0), (5, 'Manuel Akanji', 'SUI', 'Bundesliga', 'DF', 'Dortmund', 23, 1995, 25, 25, 2205, 1, 0, 0, 0, 1, 0, 0.04, 0.0, 0.04, 0.04, 0.04, 0.8, 0.8, 0.4, 0.03, 0.01, 0.05, 0.03, 0.05), (6, 'Chadrac Akolo', 'COD', 'Bundesliga', 'MF', 'Stuttgart', 23, 1995, 16, 5, 525, 0, 1, 0, 0, 0, 0, 0.0, 0.17, 0.17, 0.0, 0.17, 0.9, 0.9, 0.3, 0.16, 0.05, 0.2, 0.16, 0.2), (7, 'Kevin Akpoguma', 'GER', 'Bundesliga', 'DF', 'Hoffenheim', 23, 1995, 8, 5, 499, 0, 0, 0, 0, 2, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)  ... displaying 10 of 474 total bound parameter sets ...  (472, 'Steven Zuber', 'SUI', 'Bundesliga', 'FW', 'Stuttgart', 26, 1991, 13, 13, 1051, 5, 1, 1, 1, 3, 0, 0.43, 0.09, 0.51, 0.34, 0.43, 2.5, 1.8, 2.0, 0.22, 0.17, 0.39, 0.15, 0.33), (473, 'Steven Zuber', 'SUI', 'Bundesliga', 'MF', 'Hoffenheim', 26, 1991, 9, 6, 571, 0, 1, 0, 0, 1, 0, 0.0, 0.16, 0.16, 0.0, 0.16, 0.7, 0.7, 1.5, 0.11, 0.23, 0.34, 0.11, 0.34))
2020-09-02 18:58:14,223 INFO sqlalchemy.engine.base.Engine COMMIT
2020-09-02 18:58:14,224 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2020-09-02 18:58:14,225 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,231 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("SoccerLeagues")
2020-09-02 18:58:14,231 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,232 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("SoccerLeagues")
2020-09-02 18:58:14,233 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,234 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2020-09-02 18:58:14,235 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,236 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_xinfo("SoccerLeagues")
2020-09-02 18:58:14,236 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,239 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'SoccerLeagues' AND type = 'table'
2020-09-02 18:58:14,240 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,241 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("SoccerLeagues")
2020-09-02 18:58:14,241 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,242 INFO sqlalchemy.engine.base.Engine PRAGMA temp.foreign_key_list("SoccerLeagues")
2020-09-02 18:58:14,243 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,244 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'SoccerLeagues' AND type = 'table'
2020-09-02 18:58:14,245 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,246 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("SoccerLeagues")
2020-09-02 18:58:14,247 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,248 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_SoccerLeagues_index")
2020-09-02 18:58:14,248 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,249 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("SoccerLeagues")
2020-09-02 18:58:14,250 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,251 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_SoccerLeagues_index")
2020-09-02 18:58:14,251 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,252 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'SoccerLeagues' AND type = 'table'

2020-09-02 18:58:14,253 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,254 INFO sqlalchemy.engine.base.Engine
DROP TABLE "SoccerLeagues"
2020-09-02 18:58:14,254 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,257 INFO sqlalchemy.engine.base.Engine COMMIT
2020-09-02 18:58:14,260 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "SoccerLeagues" (
	"index" BIGINT,
	"Player_Name" TEXT,
	"Nation" TEXT,
	"League" TEXT,
	"Pos" TEXT,
	"Squad" TEXT,
	"Age" FLOAT,
	"Born" FLOAT,
	"MP" BIGINT,
	"Starts" BIGINT,
	"Min" BIGINT,
	"Gls" BIGINT,
	"Ast" BIGINT,
	"PK" BIGINT,
	"PKatt" BIGINT,
	"CrdY" BIGINT,
	"CrdR" BIGINT,
	"Gls.1" FLOAT,
	"Ast.1" FLOAT,
	"G+A" FLOAT,
	"G-PK" FLOAT,
	"G+A-PK" FLOAT,
	"xG" FLOAT,
	"npxG" FLOAT,
	"xA" FLOAT,
	"xG.1" FLOAT,
	"xA.1" FLOAT,
	"xG+xA" FLOAT,
	"npxG.1" FLOAT,
	"npxG+xA" FLOAT
)


2020-09-02 18:58:14,260 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,262 INFO sqlalchemy.engine.base.Engine COMMIT
2020-09-02 18:58:14,263 INFO sqlalchemy.engine.base.Engine CREATE INDEX "ix_SoccerLeagues_index" ON "SoccerLeagues" ("index")
2020-09-02 18:58:14,264 INFO sqlalchemy.engine.base.Engine ()
2020-09-02 18:58:14,265 INFO sqlalchemy.engine.base.Engine COMMIT
2020-09-02 18:58:14,268 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-09-02 18:58:14,287 INFO sqlalchemy.engine.base.Engine INSERT INTO "SoccerLeagues" ("index", "Player_Name", "Nation", "League", "Pos", "Squad", "Age", "Born", "MP", "Starts", "Min", "Gls", "Ast", "PK", "PKatt", "CrdY", "CrdR", "Gls.1", "Ast.1", "G+A", "G-PK", "G+A-PK", "xG", "npxG", "xA", "xG.1", "xA.1", "xG+xA", "npxG.1", "npxG+xA") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2020-09-02 18:58:14,288 INFO sqlalchemy.engine.base.Engine ((0, 'Antonio Adán', 'ESP', 'La Liga', 'GK', 'Atlético Madrid', 31.0, 1987.0, 1, 1, 90, 0, 0, 0, 0, 1, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0), (1, 'Aday', 'ESP', 'La Liga', 'DF', 'Girona', 30.0, 1987.0, 10, 8, 645, 0, 2, 0, 0, 2, 0, 0.0, 0.28, 0.28, 0.0, 0.28, 0.2, 0.2, 0.8, 0.03, 0.11, 0.14, 0.03, 0.14), (2, 'Aritz Aduriz', 'ESP', 'La Liga', 'FW', 'Athletic Club', 37.0, 1981.0, 20, 10, 943, 2, 0, 2, 2, 5, 0, 0.19, 0.0, 0.19, 0.0, 0.0, 3.3, 1.8, 0.4, 0.32, 0.04, 0.36, 0.17, 0.21), (3, 'Luis Advíncula', 'PER', 'La Liga', 'DF', 'Rayo Vallecano', 28.0, 1990.0, 28, 27, 2389, 1, 3, 0, 0, 6, 2, 0.04, 0.11, 0.15, 0.04, 0.15, 0.9, 0.9, 1.9, 0.03, 0.07, 0.1, 0.03, 0.1), (4, 'Martin Agirregabiria', 'ESP', 'La Liga', 'DF', 'Alavés', 22.0, 1996.0, 27, 23, 2032, 0, 0, 0, 0, 4, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.1, 0.4, 0.01, 0.02, 0.02, 0.01, 0.02), (5, 'Juan Aguilera', 'ESP', 'La Liga', 'MF', 'Huesca', 32.0, 1985.0, 6, 4, 344, 0, 0, 0, 0, 1, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.0, 0.13, 0.01, 0.15, 0.13, 0.15), (6, 'Carlos Akapo', 'EQG', 'La Liga', 'DF', 'Huesca', 25.0, 1993.0, 13, 12, 1023, 0, 0, 0, 0, 2, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.3, 0.3, 0.03, 0.03, 0.06, 0.03, 0.06), (7, 'Sergio Akieme', 'ESP', 'La Liga', 'DF', 'Rayo Vallecano', 20.0, 1997.0, 2, 2, 180, 0, 1, 0, 0, 0, 0, 0.0, 0.5, 0.5, 0.0, 0.5, 0.0, 0.0, 0.1, 0.0, 0.03, 0.03, 0.0, 0.03)  ... displaying 10 of 544 total bound parameter sets ...  (542, 'Martín Zubimendi', 'ESP', 'La Liga', 'MF', 'Real Sociedad', 19.0, 1999.0, 1, 0, 7, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 1.5, 1.5, 0.0, 1.5), (543, 'David Zurutuza', 'ESP', 'La Liga', 'MF', 'Real Sociedad', 32.0, 1986.0, 21, 13, 1222, 2, 0, 0, 0, 2, 0, 0.15, 0.0, 0.15, 0.15, 0.15, 1.5, 1.5, 0.3, 0.11, 0.02, 0.14, 0.11, 0.14))
2020-09-02 18:58:14,301 INFO sqlalchemy.engine.base.Engine COMMIT
2020-09-02 18:58:14,304 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2020-09-02 18:58:14,305 INFO sqlalchemy.engine.base.Engine ()

In [45]:
sqlite_connection.close()

In [46]:
#Query
engine.execute("SELECT * FROM SoccerLeagues").fetchall()

2020-09-02 18:58:16,415 INFO sqlalchemy.engine.base.Engine SELECT * FROM SoccerLeagues
2020-09-02 18:58:16,416 INFO sqlalchemy.engine.base.Engine ()

[(0, 'Antonio Adán', 'ESP', 'La Liga', 'GK', 'Atlético Madrid', 31.0, 1987.0, 1, 1, 90, 0, 0, 0, 0, 1, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (1, 'Aday', 'ESP', 'La Liga', 'DF', 'Girona', 30.0, 1987.0, 10, 8, 645, 0, 2, 0, 0, 2, 0, 0.0, 0.28, 0.28, 0.0, 0.28, 0.2, 0.2, 0.8, 0.03, 0.11, 0.14, 0.03, 0.14),
 (2, 'Aritz Aduriz', 'ESP', 'La Liga', 'FW', 'Athletic Club', 37.0, 1981.0, 20, 10, 943, 2, 0, 2, 2, 5, 0, 0.19, 0.0, 0.19, 0.0, 0.0, 3.3, 1.8, 0.4, 0.32, 0.04, 0.36, 0.17, 0.21),
 (3, 'Luis Advíncula', 'PER', 'La Liga', 'DF', 'Rayo Vallecano', 28.0, 1990.0, 28, 27, 2389, 1, 3, 0, 0, 6, 2, 0.04, 0.11, 0.15, 0.04, 0.15, 0.9, 0.9, 1.9, 0.03, 0.07, 0.1, 0.03, 0.1),
 (4, 'Martin Agirregabiria', 'ESP', 'La Liga', 'DF', 'Alavés', 22.0, 1996.0, 27, 23, 2032, 0, 0, 0, 0, 4, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.1, 0.4, 0.01, 0.02, 0.02, 0.01, 0.02),
 (5, 'Juan Aguilera', 'ESP', 'La Liga', 'MF', 'Huesca', 32.0, 1985.0, 6, 4, 344, 0, 0, 0, 0, 1, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.0, 0.13, 0.01, 0.15, 0.13, 0.15),
 (6, 'Carlos Akapo', 'EQG', 'La Liga', 'DF', 'Huesca', 25.0, 1993.0, 13, 12, 1023, 0, 0, 0, 0, 2, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.3, 0.3, 0.03, 0.03, 0.06, 0.03, 0.06),
 (7, 'Sergio Akieme', 'ESP', 'La Liga', 'DF', 'Rayo Vallecano', 20.0, 1997.0, 2, 2, 180, 0, 1, 0, 0, 0, 0, 0.0, 0.5, 0.5, 0.0, 0.5, 0.0, 0.0, 0.1, 0.0, 0.03, 0.03, 0.0, 0.03),
 (8, 'Jordi Alba', 'ESP', 'La Liga', 'DF', 'Barcelona', 29.0, 1989.0, 36, 32, 2991, 2, 8, 0, 0, 6, 0, 0.06, 0.24, 0.3, 0.06, 0.3, 1.8, 1.8, 5.1, 0.05, 0.15, 0.21, 0.05, 0.21),
 (9, 'Pedro Alcalá', 'ESP', 'La Liga', 'DF', 'Girona', 29.0, 1989.0, 25, 20, 1868, 1, 1, 0, 0, 9, 0, 0.05, 0.05, 0.1, 0.05, 0.1, 0.9, 0.9, 0.3, 0.04, 0.02, 0.06, 0.04, 0.06),
 (10, 'Rubén Alcaraz', 'ESP', 'La Liga', 'MF', 'Valladolid', 27.0, 1991.0, 34, 34, 2976, 3, 2, 0, 1, 13, 0, 0.09, 0.06, 0.15, 0.09, 0.15, 3.3, 2.6, 1.3, 0.1, 0.04, 0.14, 0.08, 0.12),
 (11, 'Álex Alegría', 'ESP', 'La Liga', 'FW', 'Rayo Vallecano', 25.0, 1992.0, 9, 0, 140, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, 0.3, 0.15, 0.17, 0.32, 0.15, 0.32),
 (12, 'Iván Alejo', 'ESP', 'La Liga', 'MF', 'Getafe', 23.0, 1995.0, 4, 2, 146, 0, 0, 0, 0, 2, 1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.1, 0.1, 0.04, 0.09, 0.13, 0.04, 0.13),
 (13, 'Carles Aleñá', 'ESP', 'La Liga', 'MF', 'Barcelona', 20.0, 1998.0, 17, 6, 637, 2, 0, 0, 0, 2, 0, 0.28, 0.0, 0.28, 0.28, 0.28, 1.5, 1.5, 0.7, 0.21, 0.09, 0.3, 0.21, 0.3),
 (14, 'Alexander', 'ARG', 'La Liga', 'DF', 'Leganés', 29.0, 1988.0, 1, 0, 10, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (15, 'Júnior Alonso', 'PAR', 'La Liga', 'DF', 'Celta Vigo', 25.0, 1993.0, 9, 6, 536, 0, 0, 0, 0, 2, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 0.4, 0.2, 0.06, 0.04, 0.1, 0.06, 0.1),
 (16, 'Sergio Álvarez', 'ESP', 'La Liga', 'GK', 'Celta Vigo', 31.0, 1986.0, 13, 13, 1170, 0, 0, 0, 0, 1, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (17, 'Sergio Álvarez', 'ESP', 'La Liga', 'MF', 'Eibar', 26.0, 1992.0, 19, 12, 1069, 0, 0, 0, 0, 1, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, 0.0, 0.02, 0.0, 0.02, 0.02, 0.02),
 (18, 'Yeray Álvarez', 'ESP', 'La Liga', 'DF', 'Athletic Club', 23.0, 1995.0, 30, 30, 2613, 0, 0, 0, 0, 10, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.4, 1.0, 0.0, 0.05, 0.0, 0.05, 0.04, 0.04),
 (19, 'Ibrahim Amadou', 'FRA', 'La Liga', 'MF', 'Sevilla', 25.0, 1993.0, 17, 7, 762, 0, 0, 0, 0, 2, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8, 0.8, 0.1, 0.09, 0.01, 0.1, 0.09, 0.1),
 (20, 'Jordi Amat', 'ESP', 'La Liga', 'DF', 'Rayo Vallecano', 26.0, 1992.0, 31, 31, 2763, 0, 0, 0, 0, 9, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7, 0.7, 0.1, 0.02, 0.0, 0.03, 0.02, 0.03),
 (21, 'Amath', 'SEN', 'La Liga', 'MF', 'Getafe', 22.0, 1996.0, 15, 13, 1002, 1, 2, 0, 0, 4, 0, 0.09, 0.18, 0.27, 0.09, 0.27, 1.6, 1.6, 0.7, 0.14, 0.07, 0.21, 0.14, 0.21),
 (22, 'Miguel Ángel Moyá', 'ESP', 'La Liga', 'GK', 'Real Sociedad', 34.0, 1984.0, 11, 11, 990, 0, 0, 0, 0, 1, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (23, 'José Ángel', 'ESP', 'La Liga', 'DF', 'Eibar', 28.0, 1989.0, 35, 34, 3028, 1, 1, 0, 0, 10, 0, 0.03, 0.03, 0.06, 0.03, 0.06, 0.7, 0.7, 3.6, 0.02, 0.11, 0.13, 0.02, 0.13),
 (24, 'Antoñito', 'ESP', 'La Liga', 'DF', 'Valladolid', 30.0, 1987.0, 30, 18, 1863, 2, 1, 0, 0, 5, 0, 0.1, 0.05, 0.14, 0.1, 0.14, 1.0, 1.0, 1.9, 0.05, 0.09, 0.14, 0.05, 0.14),
 (25, 'Vitorino Antunes', 'POR', 'La Liga', 'DF', 'Getafe', 31.0, 1987.0, 28, 25, 2181, 1, 3, 0, 0, 5, 0, 0.04, 0.12, 0.17, 0.04, 0.17, 0.9, 0.9, 2.7, 0.04, 0.11, 0.15, 0.04, 0.15),
 (26, 'Anuar', 'MAR', 'La Liga', 'MF', 'Valladolid', 23.0, 1995.0, 19, 12, 1081, 1, 0, 0, 0, 6, 0, 0.08, 0.0, 0.08, 0.08, 0.08, 2.6, 2.6, 0.1, 0.22, 0.01, 0.23, 0.22, 0.23),
 (27, 'Emmanuel Apeh', 'NGA', 'La Liga', 'MF', 'Celta Vigo', 21.0, 1996.0, 2, 0, 14, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.43, 0.43, 0.0, 0.43),
 (28, 'Mauro Arambarri', 'URU', 'La Liga', 'MF', 'Getafe', 22.0, 1995.0, 33, 32, 2676, 1, 2, 0, 0, 8, 0, 0.03, 0.07, 0.1, 0.03, 0.1, 1.4, 1.4, 1.6, 0.05, 0.05, 0.1, 0.05, 0.1),
 (29, 'Guilherme Arana', 'BRA', 'La Liga', 'MF', 'Sevilla', 21.0, 1997.0, 9, 8, 629, 0, 0, 0, 0, 3, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, 0.1, 0.03, 0.02, 0.04, 0.03, 0.04),
 (30, 'Néstor Araujo', 'MEX', 'La Liga', 'DF', 'Celta Vigo', 26.0, 1991.0, 32, 30, 2682, 3, 0, 0, 0, 3, 1, 0.1, 0.0, 0.1, 0.1, 0.1, 1.7, 1.7, 0.3, 0.06, 0.01, 0.07, 0.06, 0.07),
 (31, 'Anaitz Arbilla', 'ESP', 'La Liga', 'DF', 'Eibar', 31.0, 1987.0, 25, 22, 1950, 1, 2, 0, 0, 6, 1, 0.05, 0.09, 0.14, 0.05, 0.14, 0.8, 0.8, 0.4, 0.04, 0.02, 0.06, 0.04, 0.06),
 (32, 'Santiago Arias', 'COL', 'La Liga', 'DF', 'Atlético Madrid', 26.0, 1992.0, 25, 20, 1772, 1, 1, 0, 0, 4, 0, 0.05, 0.05, 0.1, 0.05, 0.1, 0.4, 0.4, 1.0, 0.02, 0.05, 0.07, 0.02, 0.07),
 (33, 'José Arnaiz', 'ESP', 'La Liga', 'DF', 'Leganés', 23.0, 1995.0, 6, 0, 113, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.1, 0.1, 0.05, 0.08, 0.14, 0.05, 0.14),
 (34, 'Sergio Asenjo', 'ESP', 'La Liga', 'GK', 'Villarreal', 29.0, 1989.0, 32, 32, 2880, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (35, 'Marco Asensio', 'ESP', 'La Liga', 'FW', 'Real Madrid', 22.0, 1996.0, 30, 19, 1779, 1, 4, 0, 0, 3, 0, 0.05, 0.2, 0.25, 0.05, 0.25, 4.4, 4.4, 4.0, 0.22, 0.2, 0.43, 0.22, 0.43),
 (36, 'Iago Aspas', 'ESP', 'La Liga', 'FW', 'Celta Vigo', 30.0, 1987.0, 27, 26, 2251, 20, 6, 5, 5, 5, 0, 0.8, 0.24, 1.04, 0.6, 0.84, 13.2, 9.4, 5.4, 0.53, 0.21, 0.74, 0.37, 0.59),
 (37, 'Ezequiel Ávila', 'ARG', 'La Liga', 'FW', 'Huesca', 24.0, 1994.0, 34, 20, 1997, 10, 2, 1, 1, 12, 1, 0.45, 0.09, 0.54, 0.41, 0.5, 6.7, 5.9, 2.7, 0.3, 0.12, 0.42, 0.27, 0.39),
 (38, 'Abdoulaye Ba', 'SEN', 'La Liga', 'DF', 'Rayo Vallecano', 27.0, 1991.0, 26, 25, 2110, 1, 0, 0, 0, 4, 2, 0.04, 0.0, 0.04, 0.04, 0.04, 1.2, 1.2, 0.0, 0.05, 0.0, 0.05, 0.05, 0.05),
 (39, 'Carlos Bacca', 'COL', 'La Liga', 'FW', 'Villarreal', 31.0, 1986.0, 33, 12, 1270, 6, 1, 1, 1, 3, 0, 0.43, 0.07, 0.5, 0.35, 0.43, 5.7, 5.0, 2.2, 0.41, 0.16, 0.56, 0.35, 0.51),
 (40, 'Gareth Bale', ' WAL', 'La Liga', 'FW', 'Real Madrid', 29.0, 1989.0, 29, 21, 1786, 8, 3, 1, 1, 4, 0, 0.4, 0.15, 0.55, 0.35, 0.5, 8.3, 7.6, 2.3, 0.42, 0.12, 0.53, 0.38, 0.5),
 (41, 'Mikel Balenziaga', 'ESP', 'La Liga', 'DF', 'Athletic Club', 30.0, 1988.0, 11, 6, 523, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.4, 0.0, 0.07, 0.08, 0.0, 0.08),
 (42, 'Éver Banega', 'ARG', 'La Liga', 'MF', 'Sevilla', 30.0, 1988.0, 32, 32, 2667, 3, 5, 2, 2, 17, 2, 0.1, 0.17, 0.27, 0.03, 0.2, 3.2, 1.7, 3.4, 0.11, 0.11, 0.22, 0.06, 0.17),
 (43, 'Léo Baptistão', 'BRA', 'La Liga', 'FW', 'Espanyol', 25.0, 1992.0, 20, 14, 1233, 2, 2, 1, 1, 3, 0, 0.15, 0.15, 0.29, 0.07, 0.22, 4.7, 4.0, 2.7, 0.35, 0.2, 0.54, 0.29, 0.49),
 (44, 'Enis Bardhi', 'MKD', 'La Liga', 'MF', 'Levante', 23.0, 1995.0, 36, 31, 2836, 3, 4, 0, 0, 6, 0, 0.1, 0.13, 0.22, 0.1, 0.22, 3.7, 3.7, 2.8, 0.12, 0.09, 0.21, 0.12, 0.21),
 (45, 'Antonio Barragán', 'ESP', 'La Liga', 'DF', 'Betis', 31.0, 1987.0, 14, 12, 934, 0, 0, 0, 0, 4, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, 0.8, 0.02, 0.07, 0.09, 0.02, 0.09),
 (46, 'Ander Barrenetxea', 'ESP', 'La Liga', 'FW', 'Real Sociedad', 16.0, 2001.0, 9, 5, 399, 1, 0, 0, 0, 0, 0, 0.23, 0.0, 0.23, 0.23, 0.23, 0.4, 0.4, 0.6, 0.08, 0.14, 0.22, 0.08, 0.22),
 (47, 'Marc Bartra', 'ESP', 'La Liga', 'DF', 'Betis', 27.0, 1991.0, 33, 33, 2928, 1, 0, 0, 0, 4, 0, 0.03, 0.0, 0.03, 0.03, 0.03, 0.7, 0.7, 0.3, 0.02, 0.01, 0.03, 0.02, 0.03),
 (48, 'Borja Bastón', 'ESP', 'La Liga', 'FW', 'Alavés', 25.0, 1992.0, 27, 18, 1439, 5, 1, 0, 0, 4, 0, 0.31, 0.06, 0.38, 0.31, 0.38, 5.7, 5.7, 1.1, 0.35, 0.07, 0.42, 0.35, 0.42),
 (49, 'Michy Batshuayi', 'BEL', 'La Liga', 'FW', 'Valencia', 24.0, 1993.0, 15, 4, 527, 1, 0, 0, 0, 3, 0, 0.17, 0.0, 0.17, 0.17, 0.17, 2.3, 2.3, 0.7, 0.39, 0.12, 0.5, 0.39, 0.5),
 (50, 'Jon Bautista', 'ESP', 'La Liga', 'FW', 'Real Sociedad', 23.0, 1995.0, 18, 4, 597, 1, 0, 0, 0, 1, 0, 0.15, 0.0, 0.15, 0.15, 0.15, 2.5, 2.5, 0.1, 0.37, 0.02, 0.39, 0.37, 0.39),
 (51, 'Bebé', 'POR', 'La Liga', 'FW', 'Rayo Vallecano', 28.0, 1990.0, 27, 13, 1302, 1, 1, 0, 0, 6, 0, 0.07, 0.07, 0.14, 0.07, 0.14, 1.7, 1.7, 2.3, 0.12, 0.16, 0.27, 0.12, 0.27),
 (52, 'Bebé', 'POR', 'La Liga', 'MF', 'Eibar', 28.0, 1990.0, 2, 1, 62, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, 0.2, 0.28, 0.36, 0.64, 0.28, 0.64),
 (53, 'Fran Beltrán', 'ESP', 'La Liga', 'MF', 'Celta Vigo', 19.0, 1999.0, 30, 16, 1517, 1, 0, 0, 0, 3, 0, 0.06, 0.0, 0.06, 0.06, 0.06, 0.8, 0.8, 0.7, 0.05, 0.04, 0.09, 0.05, 0.09),
 (54, 'Wissam Ben Yedder', 'FRA', 'La Liga', 'FW', 'Sevilla', 27.0, 1990.0, 35, 31, 2812, 18, 9, 2, 2, 3, 0, 0.58, 0.29, 0.86, 0.51, 0.8, 17.6, 16.0, 6.6, 0.56, 0.21, 0.77, 0.51, 0.73),
 (55, 'Karim Benzema', 'FRA', 'La Liga', 'FW', 'Real Madrid', 30.0, 1987.0, 36, 35, 2953, 21, 6, 3, 3, 1, 0, 0.64, 0.18, 0.82, 0.55, 0.73, 15.8, 13.5, 5.6, 0.48, 0.17, 0.65, 0.41, 0.58),
 (56, 'Yuri Berchiche', 'ESP', 'La Liga', 'DF', 'Athletic Club', 28.0, 1990.0, 35, 35, 3120, 2, 2, 0, 0, 8, 0, 0.06, 0.06, 0.12, 0.06, 0.12, 1.3, 1.3, 1.7, 0.04, 0.05, 0.08, 0.04, 0.08),
 (57, 'Markel Bergara', 'ESP', 'La Liga', 'MF', 'Getafe', 32.0, 1986.0, 3, 0, 53, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (58, 'Pedro Bigas', 'ESP', 'La Liga', 'DF', 'Eibar', 27.0, 1990.0, 10, 7, 585, 0, 1, 0, 0, 1, 0, 0.0, 0.15, 0.15, 0.0, 0.15, 0.2, 0.2, 0.3, 0.03, 0.04, 0.07, 0.03, 0.07),
 (59, 'Alejandro Blanco', 'ESP', 'La Liga', 'FW', 'Alavés', 19.0, 1998.0, 2, 0, 16, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (60, 'Rubén Blanco', 'ESP', 'La Liga', 'GK', 'Celta Vigo', 23.0, 1995.0, 25, 25, 2250, 0, 0, 0, 0, 2, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0),
 (61, 'Pablo de Blasis', 'ARG', 'La Liga', 'DF', 'Eibar', 30.0, 1988.0, 24, 16, 1520, 2, 0, 0, 0, 2, 1, 0.12, 0.0, 0.12, 0.12, 0.12, 1.1, 1.1, 2.1, 0.06, 0.12, 0.19, 0.06, 0.19),
 (62, 'Emmanuel Boateng', 'GHA', 'La Liga', 'FW', 'Levante', 22.0, 1996.0, 16, 7, 699, 1, 0, 0, 0, 2, 0, 0.13, 0.0, 0.13, 0.13, 0.13, 1.7, 1.7, 0.1, 0.21, 0.01, 0.22, 0.21, 0.22),
 (63, 'Kevin-Prince Boateng', 'GHA', 'La Liga', 'FW', 'Barcelona', 31.0, 1987.0, 3, 3, 239, 0, 0, 0, 0, 1, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, 0.1, 0.06, 0.05, 0.11, 0.06, 0.11),
 (64, 'Daniele Bonera', 'ITA', 'La Liga', 'DF', 'Villarreal', 37.0, 1981.0, 5, 4, 230, 0, 0, 0, 0, 1, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (65, 'Ryad Boudebouz', 'ALG', 'La Liga', 'MF', 'Betis', 28.0, 1990.0, 9, 6, 539, 0, 0, 0, 0, 1, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.6, 1.4, 0.1, 0.24, 0.34, 0.1, 0.34),
 (66, 'Ryad Boudebouz', 'ALG', 'La Liga', 'MF', 'Celta Vigo', 28.0, 1990.0, 11, 8, 717, 1, 2, 0, 0, 2, 1, 0.13, 0.25, 0.38, 0.13, 0.38, 1.0, 1.0, 2.1, 0.13, 0.26, 0.39, 0.13, 0.39),
 (67, 'Sofiane Boufal', 'MAR', 'La Liga', 'MF', 'Celta Vigo', 24.0, 1993.0, 35, 25, 2085, 3, 3, 0, 0, 6, 0, 0.13, 0.13, 0.26, 0.13, 0.26, 2.8, 2.8, 3.8, 0.12, 0.16, 0.28, 0.12, 0.28),
 (68, 'Yassine Bounou', 'MAR', 'La Liga', 'GK', 'Girona', 27.0, 1991.0, 32, 32, 2861, 0, 0, 0, 0, 2, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (69, 'Martin Braithwaite', 'DEN', 'La Liga', 'FW', 'Leganés', 27.0, 1991.0, 19, 16, 1402, 4, 5, 0, 0, 5, 0, 0.26, 0.32, 0.58, 0.26, 0.58, 3.6, 3.6, 1.9, 0.23, 0.12, 0.35, 0.23, 0.35),
 (70, 'Darko Brašanac', 'SRB', 'La Liga', 'MF', 'Alavés', 26.0, 1992.0, 24, 17, 1580, 0, 1, 0, 0, 5, 0, 0.0, 0.06, 0.06, 0.0, 0.06, 0.5, 0.5, 0.4, 0.03, 0.02, 0.05, 0.03, 0.05),
 (71, 'Rajko Brežančić', 'SRB', 'La Liga', 'DF', 'Huesca', 28.0, 1989.0, 1, 0, 67, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (72, 'Bryan', 'ESP', 'La Liga', 'MF', 'Sevilla', 17.0, 2001.0, 11, 0, 167, 1, 1, 0, 0, 0, 0, 0.54, 0.54, 1.08, 0.54, 1.08, 0.5, 0.5, 0.5, 0.25, 0.25, 0.5, 0.25, 0.5),
 (73, 'Burgui', 'ESP', 'La Liga', 'MF', 'Alavés', 24.0, 1993.0, 16, 5, 555, 1, 0, 0, 0, 1, 0, 0.16, 0.0, 0.16, 0.16, 0.16, 0.9, 0.9, 0.6, 0.15, 0.1, 0.26, 0.15, 0.26),
 (74, 'Sergio Busquets', 'ESP', 'La Liga', 'MF', 'Barcelona', 30.0, 1988.0, 35, 30, 2715, 0, 1, 0, 0, 10, 0, 0.0, 0.03, 0.03, 0.0, 0.03, 0.4, 0.4, 1.2, 0.01, 0.04, 0.05, 0.01, 0.05),
 (75, 'Unai Bustinza', 'ESP', 'La Liga', 'DF', 'Leganés', 26.0, 1992.0, 25, 24, 2023, 0, 1, 0, 0, 11, 1, 0.0, 0.04, 0.04, 0.0, 0.04, 0.2, 0.2, 0.6, 0.01, 0.03, 0.03, 0.01, 0.03),
 (76, 'Erick Cabaco', 'URU', 'La Liga', 'DF', 'Levante', 23.0, 1995.0, 21, 20, 1632, 2, 0, 0, 0, 11, 2, 0.11, 0.0, 0.11, 0.11, 0.11, 1.1, 1.1, 0.2, 0.06, 0.01, 0.07, 0.06, 0.07),
 (77, 'Gustavo Cabral', 'ARG', 'La Liga', 'DF', 'Celta Vigo', 32.0, 1985.0, 24, 21, 1897, 0, 0, 0, 0, 6, 2, 0.0, 0.0, 0.0, 0.0, 0.0, 1.3, 1.3, 0.4, 0.06, 0.02, 0.08, 0.06, 0.08),
 (78, 'Leandro Cabrera', 'URU', 'La Liga', 'DF', 'Getafe', 27.0, 1991.0, 32, 31, 2794, 2, 0, 0, 0, 11, 1, 0.06, 0.0, 0.06, 0.06, 0.06, 1.9, 1.9, 0.4, 0.06, 0.01, 0.08, 0.06, 0.08),
 (79, 'Jordi Calavera', 'ESP', 'La Liga', 'DF', 'Eibar', 22.0, 1995.0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (80, 'Fernando Calero', 'ESP', 'La Liga', 'DF', 'Valladolid', 22.0, 1995.0, 36, 35, 3130, 1, 0, 0, 0, 7, 0, 0.03, 0.0, 0.03, 0.03, 0.03, 0.6, 0.6, 0.2, 0.02, 0.01, 0.02, 0.02, 0.02),
 (81, 'Jonathan Calleri', 'ARG', 'La Liga', 'FW', 'Alavés', 24.0, 1993.0, 34, 33, 2869, 9, 2, 2, 2, 6, 0, 0.28, 0.06, 0.35, 0.22, 0.28, 7.2, 5.7, 2.1, 0.23, 0.07, 0.29, 0.18, 0.25),
 (82, 'Juanjo Camacho', 'ESP', 'La Liga', 'MF', 'Huesca', 37.0, 1980.0, 3, 0, 37, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.1, 0.3, 0.2, 0.76, 0.96, 0.2, 0.96),
 (83, 'Sergio Camello', 'ESP', 'La Liga', 'FW', 'Atlético Madrid', 17.0, 2001.0, 1, 0, 45, 1, 0, 0, 0, 0, 0, 2.0, 0.0, 2.0, 2.0, 2.0, 0.6, 0.6, 0.1, 1.15, 0.17, 1.32, 1.15, 1.32),
 (84, 'José Campaña', 'ESP', 'La Liga', 'MF', 'Levante', 25.0, 1993.0, 36, 36, 3210, 4, 9, 0, 0, 11, 0, 0.11, 0.25, 0.36, 0.11, 0.36, 1.5, 1.5, 4.0, 0.04, 0.11, 0.15, 0.04, 0.15),
 (85, 'Sergio Canales', 'ESP', 'La Liga', 'MF', 'Betis', 27.0, 1991.0, 32, 30, 2655, 7, 2, 2, 2, 5, 0, 0.24, 0.07, 0.31, 0.17, 0.24, 6.7, 5.2, 5.8, 0.23, 0.2, 0.42, 0.18, 0.37),
 (86, 'Ander Capa', 'ESP', 'La Liga', 'DF', 'Athletic Club', 26.0, 1992.0, 25, 17, 1642, 0, 0, 0, 0, 9, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6, 0.6, 1.0, 0.03, 0.05, 0.08, 0.03, 0.08),
 (87, 'Marc Cardona', 'ESP', 'La Liga', 'FW', 'Eibar', 23.0, 1995.0, 17, 6, 604, 3, 1, 0, 0, 1, 0, 0.45, 0.15, 0.6, 0.45, 0.6, 2.7, 2.7, 0.6, 0.41, 0.1, 0.5, 0.41, 0.5),
 (88, 'Daniel Carriço', 'POR', 'La Liga', 'DF', 'Sevilla', 29.0, 1988.0, 24, 24, 2130, 1, 1, 0, 0, 10, 0, 0.04, 0.04, 0.08, 0.04, 0.08, 0.7, 0.7, 0.7, 0.03, 0.03, 0.06, 0.03, 0.06),
 (89, 'Guido Carrillo', 'ARG', 'La Liga', 'FW', 'Leganés', 27.0, 1991.0, 32, 23, 1992, 6, 1, 1, 3, 5, 0, 0.27, 0.05, 0.32, 0.23, 0.27, 8.6, 6.3, 1.3, 0.39, 0.06, 0.45, 0.29, 0.35),
 (90, 'Dani Carvajal', 'ESP', 'La Liga', 'DF', 'Real Madrid', 26.0, 1992.0, 24, 23, 2107, 1, 2, 0, 0, 10, 0, 0.04, 0.09, 0.13, 0.04, 0.13, 0.4, 0.4, 3.2, 0.02, 0.14, 0.16, 0.02, 0.16),
 (91, 'William Carvalho', 'POR', 'La Liga', 'MF', 'Betis', 26.0, 1992.0, 30, 26, 2385, 0, 5, 0, 0, 7, 0, 0.0, 0.19, 0.19, 0.0, 0.19, 0.6, 0.6, 2.0, 0.02, 0.07, 0.1, 0.02, 0.1),
 (92, 'Casemiro', 'BRA', 'La Liga', 'MF', 'Real Madrid', 26.0, 1992.0, 29, 27, 2312, 3, 0, 0, 0, 7, 1, 0.12, 0.0, 0.12, 0.12, 0.12, 1.8, 1.8, 0.7, 0.07, 0.03, 0.09, 0.07, 0.09),
 (93, 'Santiago Cáseres', 'ARG', 'La Liga', 'MF', 'Villarreal', 21.0, 1997.0, 23, 17, 1588, 0, 1, 0, 0, 10, 0, 0.0, 0.06, 0.06, 0.0, 0.06, 0.3, 0.3, 0.9, 0.02, 0.05, 0.07, 0.02, 0.07),
 (94, 'Catena', 'ESP', 'La Liga', 'DF', 'Rayo Vallecano', 23.0, 1994.0, 2, 2, 176, 0, 0, 0, 0, 1, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.1, 0.0, 0.03, 0.0, 0.03, 0.03, 0.03),
 (95, 'Santi Cazorla', 'ESP', 'La Liga', 'MF', 'Villarreal', 33.0, 1984.0, 35, 30, 2647, 4, 10, 2, 3, 2, 0, 0.14, 0.34, 0.48, 0.07, 0.41, 4.3, 2.0, 6.7, 0.15, 0.23, 0.38, 0.07, 0.3),
 (96, 'Dani Ceballos', 'ESP', 'La Liga', 'MF', 'Real Madrid', 21.0, 1996.0, 23, 13, 1248, 3, 0, 0, 0, 3, 0, 0.22, 0.0, 0.22, 0.22, 0.22, 2.3, 2.3, 1.7, 0.16, 0.12, 0.29, 0.16, 0.29),
 (97, 'Charles', 'BRA', 'La Liga', 'FW', 'Eibar', 34.0, 1984.0, 34, 17, 1739, 14, 1, 6, 7, 4, 0, 0.72, 0.05, 0.78, 0.41, 0.47, 11.6, 6.3, 1.0, 0.6, 0.05, 0.65, 0.33, 0.38),
 (98, 'Chechu', 'ESP', 'La Liga', 'DF', 'Rayo Vallecano', 36.0, 1982.0, 1, 1, 90, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (99, 'Chema', 'ESP', 'La Liga', 'DF', 'Levante', 26.0, 1992.0, 19, 13, 1254, 2, 0, 0, 0, 7, 0, 0.14, 0.0, 0.14, 0.14, 0.14, 0.6, 0.6, 0.1, 0.04, 0.01, 0.05, 0.04, 0.05),
 (100, 'Denis Cheryshev', 'RUS', 'La Liga', 'MF', 'Valencia', 27.0, 1990.0, 27, 19, 1706, 2, 2, 0, 0, 2, 0, 0.11, 0.11, 0.21, 0.11, 0.21, 3.3, 3.3, 6.7, 0.17, 0.36, 0.53, 0.17, 0.53),
 (101, 'Leandro Chichizola', 'ARG', 'La Liga', 'GK', 'Getafe', 28.0, 1990.0, 1, 1, 90, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (102, 'Samuel Chukwueze', 'NGA', 'La Liga', 'FW', 'Villarreal', 19.0, 1999.0, 26, 19, 1706, 5, 2, 0, 0, 2, 0, 0.26, 0.11, 0.37, 0.26, 0.37, 5.2, 5.2, 1.5, 0.28, 0.08, 0.36, 0.28, 0.36),
 (103, 'Jasper Cillessen', 'NED', 'La Liga', 'GK', 'Barcelona', 29.0, 1989.0, 3, 3, 270, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (104, 'Coke', 'ESP', 'La Liga', 'DF', 'Levante', 31.0, 1987.0, 27, 19, 1817, 4, 0, 0, 0, 5, 1, 0.2, 0.0, 0.2, 0.2, 0.2, 1.2, 1.2, 1.5, 0.06, 0.07, 0.13, 0.06, 0.13),
 (105, 'Álex Collado', 'ESP', 'La Liga', 'FW', 'Barcelona', 19.0, 1999.0, 1, 0, 85, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.1, 0.0, 0.13, 0.0, 0.13, 0.13, 0.13),
 (106, 'Santi Comesaña', 'ESP', 'La Liga', 'MF', 'Rayo Vallecano', 21.0, 1996.0, 25, 23, 2032, 1, 1, 0, 0, 6, 0, 0.04, 0.04, 0.09, 0.04, 0.09, 0.8, 0.8, 0.3, 0.03, 0.01, 0.05, 0.03, 0.05),
 (107, 'Duje Čop', 'CRO', 'La Liga', 'FW', 'Valladolid', 28.0, 1990.0, 18, 6, 687, 0, 0, 0, 0, 2, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.8, 2.8, 1.2, 0.36, 0.15, 0.52, 0.36, 0.52),
 (108, 'Francis Coquelin', 'FRA', 'La Liga', 'MF', 'Valencia', 27.0, 1991.0, 26, 20, 1761, 0, 1, 0, 0, 5, 0, 0.0, 0.05, 0.05, 0.0, 0.05, 0.4, 0.4, 0.7, 0.02, 0.04, 0.06, 0.02, 0.06),
 (109, 'Iñigo Córdoba', 'ESP', 'La Liga', 'FW', 'Athletic Club', 21.0, 1997.0, 23, 15, 1321, 0, 4, 0, 0, 3, 0, 0.0, 0.27, 0.27, 0.0, 0.27, 1.3, 1.3, 1.1, 0.09, 0.07, 0.16, 0.09, 0.16),
 (110, 'Ángel Correa', 'ARG', 'La Liga', 'MF', 'Atlético Madrid', 23.0, 1995.0, 36, 20, 1919, 3, 2, 0, 0, 7, 1, 0.14, 0.09, 0.23, 0.14, 0.23, 2.2, 2.2, 4.4, 0.1, 0.21, 0.31, 0.1, 0.31),
 (111, 'Diego Costa', 'ESP', 'La Liga', 'FW', 'Atlético Madrid', 29.0, 1988.0, 16, 14, 1112, 2, 2, 0, 0, 4, 1, 0.16, 0.16, 0.32, 0.16, 0.32, 1.6, 1.6, 1.7, 0.13, 0.14, 0.26, 0.13, 0.26),