In [1]:
# Imports 
import pandas as pd

In [4]:
# get files to load

e_file = "resources/english.csv"
g_file = "resources/german.csv"
s_file = "resources/spanish.csv"

In [5]:
#load data into pandas dataframe

english = pd.read_csv(e_file)
german = pd.read_csv(g_file)
spanish = pd.read_csv(s_file)

In [7]:
english.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Playing Time,Playing Time.1,Playing Time.2,...,Per 90 Minutes.4,Expected,Expected.1,Expected.2,Per 90 Minutes.5,Per 90 Minutes.6,Per 90 Minutes.7,Per 90 Minutes.8,Per 90 Minutes.9,Unnamed: 29
0,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,G+A-PK,xG,npxG,xA,xG,xA,xG+xA,npxG,npxG+xA,Matches
1,1,Patrick van Aanholt\Patrick-van-Aanholt,nl NED,DF,Crystal Palace,27,1990,36,36,3195,...,0.14,2.7,2.7,3.9,0.08,0.11,0.19,0.08,0.19,Matches
2,2,Sergio Agüero\Sergio-Aguero,ar ARG,FW,Manchester City,30,1988,33,31,2459,...,0.99,20.7,19.2,5.5,0.76,0.2,0.96,0.7,0.91,Matches
3,3,Nathan Aké\Nathan-Ake,nl NED,DF,Bournemouth,23,1995,38,38,3411,...,0.11,3.4,3.4,0.8,0.09,0.02,0.11,0.09,0.11,Matches
4,4,Marc Albrighton\Marc-Albrighton,eng ENG,FWMF,Leicester City,28,1989,27,18,1625,...,0.22,1.1,1.1,3.1,0.06,0.17,0.23,0.06,0.23,Matches

In [8]:
german.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Playing Time,Playing Time.1,Playing Time.2,...,Per 90 Minutes.4,Expected,Expected.1,Expected.2,Per 90 Minutes.5,Per 90 Minutes.6,Per 90 Minutes.7,Per 90 Minutes.8,Per 90 Minutes.9,Unnamed: 29
0,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,G+A-PK,xG,npxG,xA,xG,xA,xG+xA,npxG,npxG+xA,Matches
1,1,Issah Abbas\Issah-Abbas,gh GHA,FW,Mainz 05,19,1998,1,0,9,...,0,0,0,0,0.17,0,0.17,0.17,0.17,Matches
2,2,David Abraham\David-Abraham,ar ARG,DF,Eint Frankfurt,32,1986,17,17,1420,...,0,0.4,0.4,0.1,0.03,0.01,0.03,0.03,0.03,Matches
3,3,Amir Abrashi\Amir-Abrashi,al ALB,MF,Freiburg,28,1990,10,9,790,...,0,0.2,0.2,0.1,0.02,0.01,0.02,0.02,0.02,Matches
4,4,Tyler Adams\Tyler-Adams,us USA,MF,RB Leipzig,19,1999,10,8,721,...,0.25,0.2,0.2,0.7,0.03,0.09,0.12,0.03,0.12,Matches

In [9]:
spanish.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Playing Time,Playing Time.1,Playing Time.2,...,Per 90 Minutes.4,Expected,Expected.1,Expected.2,Per 90 Minutes.5,Per 90 Minutes.6,Per 90 Minutes.7,Per 90 Minutes.8,Per 90 Minutes.9,Unnamed: 29
0,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,G+A-PK,xG,npxG,xA,xG,xA,xG+xA,npxG,npxG+xA,Matches
1,1,Antonio Adán\Antonio-Adan,es ESP,GK,Atlético Madrid,31,1987,1,1,90,...,0,0,0,0,0,0,0,0,0,Matches
2,2,Aday\Aday,es ESP,DFMF,Girona,30,1987,10,8,645,...,0.28,0.2,0.2,0.8,0.03,0.11,0.14,0.03,0.14,Matches
3,3,Aritz Aduriz\Aritz-Aduriz,es ESP,FW,Athletic Club,37,1981,20,10,943,...,0,3.3,1.8,0.4,0.32,0.04,0.36,0.17,0.21,Matches
4,4,Luis Advíncula\Luis-Advincula,pe PER,DF,Rayo Vallecano,28,1990,28,27,2389,...,0.15,0.9,0.9,1.9,0.03,0.07,0.1,0.03,0.1,Matches